disabled_rules:
- trailing_whitespace
- colon
- comma
- control_statement
- opening_brace
- vertical_whitespace
- weak_delegate
- comment_spacing

opt_in_rules:
- empty_count
- empty_string

excluded:
- Carthage
- Pods
- SwiftLint/Common/3rdPartyLib

force_cast: warning # implicitly
force_try:
severity: warning # explicitly


colon:
- flexible_right_spacing: true

# implicitly
line_length: 200

warning: 200
error: 300
ignores_function_declarations: true
ignores_comments: true
ignores_urls: true

function_body_length:
warning: 300
error: 500

function_parameter_count:
warning: 6
error: 8

type_body_length:
warning: 300
error: 500

file_length:
warning: 1000
error: 1500
ignore_comment_only_lines: true

cyclomatic_complexity:
warning: 15
error: 25

weak_delegate:
    excluded: ".*Test\\.swift"

reporter: "xcode"
